### PR TITLE
feat: multiline text overflow ellipsis

### PR DESCRIPTION
**Pull request by LuciNyan**
### Description
1. Support multiline text overflow ellipsis(webkit-line-clamp + webkit-box-orient).

2. Fixed a bug where overflow: 'hidden' should not be inherited by child elements.

3. Support the 'line-clamp' property, including custom block ellipsis.

I added display: block here because whether it's required by the CSS draft or needed to implement this feature (must be different from display: flex), it seems I have to do so. One thing I want to discuss here is whether we can set the default display to flex, because this is more in line with the original behavior of the browser and does not seem to cause any problems (can pass all unit tests).

https://github.com/vercel/satori/assets/22126563/5ec006a7-9cfb-4fc4-9000-adc9fb042c17

https://github.com/vercel/satori/assets/22126563/d672942e-e2c9-423c-8bcf-23a932e7cfb3

Closes: #253

### CODE REVIEW

**Comment by shuding** [comment]
Wow I've been dreaming about this feature for a long time, thank you for bringing it to life!

**Comment by shuding** [comment]
I think we should drop the `-webkit-` prefix (we did that for `-webkit-text-fill-color`) as Satori wants to support the standard but not specifically for a browser. Or a better idea is to support both for [compatibility](https://drafts.csswg.org/css-overflow-4/#webkit-line-clamp).

**Comment by LuciNyan** [comment]
> Wow I've been dreaming about this feature for a long time, thank you for bringing it to life!

Thank you so much for your kind words! 😆

**Comment by LuciNyan** [comment]
> Or a better idea is to support both for [compatibility](https://drafts.csswg.org/css-overflow-4/#webkit-line-clamp).

Haha, I was thinking the same, so I marked it as WIP. XD

**Comment by shuding** [comment]
It seems a bit weird when using `text-align: center`: [example](https://satori-playground-git-fork-lucinyan-feat-multiline-text-ba6379.vercel.sh/?share=ZZLBTsMwDIZfxbKEdpmgTEOgCJDQxIEDpyHtskvauG22NKmSlK1UfXeSdt3EuLTJb8e_PycdZkYQMnwW8nurAZxvFb10XVwDCOlqxVsGs1zRcTYf1ZJkUfog3ifJzSQepPDllcaVLPSHp8qFQEbak51Cu8Z5mbcrE0Qda_0N50HfnGwek-SkpjzbF9Y0WoQDh1J6GvP7fqtf42KiuOYAqLkQUhfh3CKpj_AQPpPX6LaWP8RgOVmdgZZndwBPR_8Wmf71G3ozVpCNAwjlnVFSgCVxiV9GmSqT7S8BJTWtFK9qBouTGHkABiKAT74PjYMvCTaU3sK6qcnm3PkB-C4Qh8Tpj3M0tZdGO2QdDgjIngICjpeGLPKgoLQpkOVcOZojVWYnv9o6vgN_GHahThzKe5WSQOZtQ_0cPU9DhuVNVhbY_wI)

**Comment by LuciNyan** [comment]
> It seems a bit weird when using `text-align: center`: [example](https://satori-playground-git-fork-lucinyan-feat-multiline-text-ba6379.vercel.sh/?share=ZZLBTsMwDIZfxbKEdqmgTEOgCJDQxIEDpyHtskvauG22NKmalK5UfXeSdt3EuLTJb8e_Pyc9pkYQMnwW8nunAazrFL30fVgDCGkrxTsGi0zRcRFNakEyL5wX7-P4ZhZbKVxxpXElc_3hqLQ-kJJ2VM-hfWOdzLq18aIOtf6GM69vTzaPcXxSE54e8to0WvgDbSEdTfnDsNOvYTFTXHMAVFwIqXN_bhlXR3jwn9lrctvIH2Kwmq3OQKuzO4Cjo3sLTP_69b2ZWlAdBuDLW6OkgJrEJX4ZZaJMergElNS0VrysGCxPYuABGIkAPvnBNw6uINhScgubpqI649aNwHee2CfOf4zQVE4abZH1OCIge_IIOF0assCDgpImR5ZxZSlCKs1efnVVeAeuHXe-ThjKe5mQQObqhoYIHU98RkFKmdbUSuDwCw)

Hey Shu, thanks for the feedback! I’ve updated the PR with all the changes.

**Comment by Jackie1210** [comment]
nice work！

**Review by shuding — APPROVED** [review]
Thank you, this is good to land!

**Pull request merged**
