### PR TITLE
fix: alphabetic emoji

### PR DESCRIPTION
**Pull request by LuciNyan**
### Description
Regarding the Line Breaking Classes classification, emojis can be classified as "Alphabetic", "Ideographic", "Emoji Base", or "Emoji Modifier". However, some emojis, like ⚡️, are classified as "Alphabetic" because they may come from a writing system. According to the UNICODE LINE BREAKING ALGORITHM, in some cases, a line cannot break after an "Alphabetic" character, which is how browsers handle it. This can create an issue when splitting text based on line breaks, as some emojis may mix with text to form a "word" like "[emoji]abc". Therefore, when calculating "wordPositionInLayout", we need to separate emojis and text more carefully.

I noticed that the code in the "src/text.ts" file seems a bit messy. The function is quite long, and I'd like to know your thoughts on whether we could break it down to improve readability. This would help me adjust my coding habits in the future. Cuz I've heard that some programmers with competitive programming backgrounds really like long functions, haha 😆

Also, I had a question. I'm not sure why some of the test screenshots show slight variations... Do you have any ideas? 🤔

image

image

image

Closes: #422

### CODE REVIEW

**Comment by shuding** [comment]
> I noticed that the code in the "src/text.ts" file seems a bit messy. The function is quite long, and I'd like to know your thoughts on whether we could break it down to improve readability.

We need to refactor that function a bit, of course! It was growing while adding new features and fixes incrementally, definitely not planned. :)

**Review by shuding — COMMENTED** [review]
Thanks for fixing this! The change looks good to me, but I'm wondering why test/__image_snapshots__/dynamic-size-test-tsx-test-dynamic-size-test-tsx-dynamic-size-should-render-image-with-dynamic-width-1-snap.png has white background added now 🤔

**Comment by LuciNyan** [comment]
> Thanks for fixing this! The change looks good to me, but I'm wondering why test/**image_snapshots**/dynamic-size-test-tsx-test-dynamic-size-test-tsx-dynamic-size-should-render-image-with-dynamic-width-1-snap.png has white background added now (it should, according to the code)... 🤔

I added the white background to the snapshot image to make it clearer and easier to confirm that the code changes didn't cause any unintended effects. 😆 If you think removing the background would be better, I'm happy to do that. Just let me know!

**Comment by LuciNyan** [comment]
> We need to refactor that function a bit, of course! It was growing while adding new features and fixes incrementally, definitely not planned. :)

I'd be happy to help with the refactoring! Let's clean up that function and make it more organized! 😄

**Comment by LuciNyan** [comment]
I've removed the background color and updated the snapshot. The PR is ready to go! 🚀

**Pull request merged**
