### PR TITLE
fix: incorrect data URL parsing

### LINKED ISSUE #592: Image in SVG doesn't work when exported to PNG
# Bug report

## Description / Observed Behavior

Image in SVG doesn't seem to work when exported to PNG – it throws this error:

```
Cannot read properties of undefined (reading '0')
```

CleanShot 2024-02-15 at 15 33 37

## Expected Behavior

Render the PNG the same way as it does the SVG.

## Reproduction

Repro: https://d.to/k3beO8I

(click on the "PNG" tab)

## Additional Context

Related PR: https://github.com/vercel/satori/pull/472

cc: @Jackie1210

### LINKED ISSUE #597: Satori cannot render svg data URI with comma inside
# Bug report

## Description / Observed Behavior

If charset is specified, satori cannot render svg data URI that contains `,` (comma).

svg in data URI with charset set and comma inside errors

## Expected Behavior

satori successfully renders the svg.

svg in data URI with charset set and comma inside renders well

## Reproduction

https://og-playground.vercel.app/?share=bZDLboQwDEV_BbnLUghtR4IUWFTqH3TJYniEkDYQRMyEEeLf69DtREqU63v8kHdoTSeAQ65GGdilLfZrV2PN1VhLEdubfN5G_dEO9WIFFiv2L2mYUzig8GSLCgbEmcexcy5yb5FZZPzKGPOZFfxDfNNq-n2IJlmWxadN8E0sVpmJwCRKvFbCfZqNNAtYkLDzVlDms9F3aaagV1qT-9SfhzJmoyb0Q11YeNJhegn8Q15c5n6o8nrQF0IwM1IzC3wHpzocgKfEwyCUHBD4uxedaFYJvK-1FSGI0fyo7_vs14XuVFSnNxN-jY3ogOOyiiMErBsiBqG1cWbRHRx_

## Additional Context

Satori version, and any other context about the problem here.

It seems that data URI parsing is based on incorrect regex.
[Original Specification](https://www.rfc-editor.org/rfc/rfc2397#section-3)

### PR DESCRIPTION
**Pull request by kiwiyou**
Fixes #597 with correct regex.

[Data URL Specification](https://www.rfc-editor.org/rfc/rfc2397#section-3)

### CODE REVIEW

**Comment by steven-tey** [comment]
Just tested this out, doesn't seem to work: [playground link](https://satori-playground-git-fork-kiwiyou-fix-nested-svg.vercel.sh/?share=dVPtbpswFH0V5GniTxQbSNiCQqWt3bTPP2ulStMkRPDFODU2wyaQRnn32Wm3wtIiIXHPObo-5_pyQIWigBK0pnz3S3qPjzZ7Aenh8IR4XgWcVSbx_ICQ1_5sTPWcmupZhnLdiHxvuVLAMOUccsVbKAxX0ioKJbpaTjW54Ex-NlBrJwBpoJ0Ktp02vNxfKktJ5-450SYv7lirOkkvlVCtVb0qy_I_N7bDNb-HxIvCM-L2MXtMyIg7Hv9-XzyBa71jZ7NJ3Wj882me4zsO_Xs1pD7xiGdJ904EJRci9aWSMIGHWkid-pUxTYJx3_fzPpqrluGQEIKtp5F65Nb65XXOYIx4Hqepf4JJFmTh5JwXA70cyTItlA_etDVnonlpCirnEgzeNgyTEK-WOIzxIsZRTLKPWbhahvEifrPMCtF__Tko9q4avl2v9FUQRzfs7j64_f5J_w5-fJnbBpPT8PguXPB_9RrbHb9AM6Qat3EaJQd0CoOSt_Ze0YN_lCxcQWHTMZSUudAwQ1CrLb_ZN-5PMf2psn3cZnyoN0BRYtoOjjNk8o1VVCCE6lUrKDr-AQ)

CleanShot 2024-03-05 at 18 46 00@2x

**Comment by kiwiyou** [comment]
@steven-tey Thank you for your report. I found out that this PR fixes an another issue. Updated issue number.

**Comment by shuding** [comment]
Thanks @kiwiyou! Could you please add a test case for it so it won't regress in the future?

**Comment by kiwiyou** [comment]
@shuding Added 2 tests. I deliberately excluded tests for unsupported charsets. (e.g. `charset=iso-8859-7`)

**Comment by steven-tey** [comment]
Really appreciate your work on this @kiwiyou, but from the latest [preview URL](https://satori-playground-dplu3elt5.vercel.sh/?share=dVPtbpswFH0V5GniTxQbSNiCQqWt3bTPP2ulStMkRPDFODU2wyaQRnn32Wm3wtIiIXHPObo-5_pyQIWigBK0pnz3S3qPjzZ7Aenh8IR4XgWcVSbx_ICQ1_5sTPWcmupZhnLdiHxvuVLAMOUccsVbKAxX0ioKJbpaTjW54Ex-NlBrJwBpoJ0Ktp02vNxfKktJ5-450SYv7lirOkkvlVCtVb0qy_I_N7bDNb-HxIvCM-L2MXtMyIg7Hv9-XzyBa71jZ7NJ3Wj882me4zsO_Xs1pD7xiGdJ904EJRci9aWSMIGHWkid-pUxTYJx3_fzPpqrluGQEIKtp5F65Nb65XXOYIx4Hqepf4JJFmTh5JwXA70cyTItlA_etDVnonlpCirnEgzeNgyTEK-WOIzxIsZRTLKPWbhahvEifrPMCtF__Tko9q4avl2v9FUQRzfs7j64_f5J_w5-fJnbBpPT8PguXPB_9RrbHb9AM6Qat3EaJQd0CoOSt_Ze0YN_lCxcQWHTMZSUudAwQ1CrLb_ZN-5PMf2psn3cZnyoN0BRYtoOjjNk8o1VVCCE6lUrKDr-AQ), this doesn't seem to work:

CleanShot 2024-03-18 at 23 38 09@2x

(PNG tab)

**Comment by kiwiyou** [comment]
@shuding Could you review this PR?

**Comment by ducan-ne** [comment]
it still doesn't seem to work in my case too, [Playground url](https://satori-playground-git-fork-kiwiyou-fix-nested-svg.vercel.sh/?share=dVRtb5swEP4rlqepm5SAgUASlOxDX6RWWrd1rRZNijQZMODMYIoN5EX57zvysjakvS_Yz3Pn8z13ZoNDGTHs40nE63mOkNIrwaabTbtGKGU8SbWPLixCPl709mDDI512sIirQtAVoLFgyyParq95yULNZQ5cKEWV5UeWCp7kd5plqqVYrll5pBaV0jxeXUkA8zb_KR3Q8G9SyiqPrqSQJfAf4jj-nxWiHvma-cixX0GzQy0eITt0u53nX2AxUXWy9zraMhO5ms5xqnXhm2bTNEbjGLJMTJsQYrb--DRiJ8l0YwFvjIbucGjbA2s4dseQ47XfXs_pxnNIh6k5ay7lErISRND5QQhCDNcllmO7NvGGg_Gge4nT1r3YuVoli45iHa1V42XX6vLKJhGLVQcDNBS8-EF1esYAVwCOIijn3hmPjZFjIRu-njVILeJ6UJtXDwYjqOj2wK_nGJnnOcx3kkzMN-404RlNWPeMQ3Nc0tX8pR9vciWLD0OgYApCJhq1jpMw41EQBTx_pmtDVQUNqGJGKE2lZQnZzdoyZbCAmTeLKhA8NKlSTCsT5uePzejXa-f3giw9usyXtzd3o5-z59nD7PLKfBC_6ln8ePPtvukPnx6-12KcXff7_ZgL1m01QrqkuYplmcEVS6mpZp8cmBvLsF0XeSPHGI68z92wU30n7SQDAlLyGr64h2XRvlSF_Q3eqYb9EbwWvJcJ-4N2E7GgSrAfU6FYD7NMLvjTqmj_IbrZ7eCc9r3dZAGLsK_Lim17WNMAPFImhGxkKSK8_Qc)

**Comment by kiwiyou** [comment]
@ducan-ne It works on my machine, could you describe the step to reproduce the bug?

**Comment by ducan-ne** [comment]
@kiwiyou I don't know it just shows me a error when use the playground
CleanShot 2024-05-04 at 17 23 17@2x

**Comment by kiwiyou** [comment]
@ducan-ne [Your example works fine.](https://satori-playground-git-fork-kiwiyou-fix-nested-svg.vercel.sh/?share=bVPbjpswEP0Vy1W1rZSAuROU9GEv7Vbqtt3uavMSqTJgwKnBLDYhF-XfOyRhb-2Tx-eM53JmvMOJTBmO8DTlq0WFkNIbwWa7XW8jVDCeFzpCZxYh789GR7DjqS7eYClXtaAbQDPB1gPa25e8YYnmsgIukaItq4GlgufVV81K1VOs0qwZqGWrNM82FxLAqs__mo5p8idvZFulF1LIBvh3WZY9ZYVXd3zLIuTYL6D5qRefkAO63y-qT70xVav86LYuRaVmC1xoXUem2XWd0TmGbHLTJoSYvR9-ocFsZwFuhIEXBLbtWpPAm0DQZ-FmO98hJ2TFWXcu1xCdIIL-fYjA1fA8Yjm2ZxM_cCfukOz1TP7XfsPSofu-LYQOjUFrKcvUyYZbInj9k-riCQGshjtKoawbZzIxQsdCNpy-5RYW8Xyo0V-5bgiVXZ_47QIj8zmm-Sbo1HyRc8pLmrPB9ySaRwZNnnV6hTUsOw1BwRQSJjq1zfKk5Gkax7x6pFtDtTWNqWJGIk2lZQNZzJVlyngJy2bWbSx4YlKlmFYmzO-3zei3S2ez9NfUr9bXVyL8dTt__DI_n1_ciocu-3x3dfO9Gwf3tz8erPpyPB5nXLBhAAjphlYqk00JhTVSU80-ODBFy7A9D_mhYwSh_3FwP6oz7fcFLBCEr-DEIyzr_iMoHO3wQQschbCM-CgCjtz-krK4zXGUUaHYCLNSLvn9pu6_qO4ON4jTr_NVGbMUR7pp2X6ENY3Bo2BCyE42IsX7vw) Did you use the playground provided for this PR?

**Comment by kiwiyou** [comment]
@shuding Do you have any blockades for the review?

**Comment by ducan-ne** [comment]
@kiwiyou it works the first time but not after that, try enter something to the editor (use my reproduce url)

**Comment by kiwiyou** [comment]
@ducan-ne Your problem seems to be the case for #592, not #597 here.

**Review by shuding — APPROVED** [review]
Thank you!

**Review by shuding — APPROVED** [review]
Thank you!

**Pull request merged**
