### PR TITLE
fixes 183 backgroundImage with url

### PR DESCRIPTION
**Pull request by Sam-Apostel**
The <pattern> element needs to have the same offset as the target rect for `url()`-style backgrounds.

Before:
Screenshot 2022-10-15 at 11 07 12

After:
Screenshot 2022-10-15 at 11 06 15

### CODE REVIEW

**Comment by shuding** [comment]
Van you add a test case?

**Comment by Sam-Apostel** [comment]
should I first commit the failing test for visual confirmation or is a passing test good enough?

**Comment by Sam-Apostel** [comment]
broken test: 
image-test-tsx-test-image-test-tsx-2-m-22-m-image-2-m-22-mbackground-image-url-2-m-22-mshould-correctly-position-the-background-pattern-1-snap

passing test: 
image-test-tsx-test-image-test-tsx-2-m-22-m-image-2-m-22-mbackground-image-url-2-m-22-mshould-correctly-position-the-background-pattern-1-snap

**Review by shuding — APPROVED** [review]
Amazing, thank you!

**Pull request merged**
