### PR TITLE
Add support for passing in `0` as first argument to `linear-gradient` and `repeating-linear-gradient` + color model tests

### PR DESCRIPTION
**Pull request by jueungrace**
- Adds test file for color models + correlated snapshots
- Adds demo tab for testing color models (open to removing this, just added personally to play around with!)
- Updated `background-image.ts` to check for zero values when evaluating `linear-gradient` related properties (and sets equal to a directional `to top` value)

### CODE REVIEW

**Comment by shuding** [comment]
Thank you so much @jueungrace, PR looks great! Can you remove the test/__image_snapshots__/__diff_output__/color-models-test-tsx-test-color-models-test-tsx-2-m-22-m-color-models-2-m-22-mbackground-color-and-color-2-m-22-mshould-support-currentcolor-1-snap-diff.png file? Seems like unintended

**Comment by jueungrace** [comment]
> Thank you so much @jueungrace, PR looks great! Can you remove the test/**image_snapshots**/**diff_output**/color-models-test-tsx-test-color-models-test-tsx-2-m-22-m-color-models-2-m-22-mbackground-color-and-color-2-m-22-mshould-support-currentcolor-1-snap-diff.png file? Seems like unintended

Yes, updated the snapshots and removed the unwanted diffs! :)

**Comment by shuding** [comment]
Amazing work! 🎉

**Comment by LouisCuvelier** [comment]
Hi @shuding 

Is repeating-linear-gradient supported ? It seems to not work on Next 13.5.1

**Comment by shuding** [comment]
@LouisCuvelier Could you try testing it in the playground (https://og-playground.vercel.app) to see if it works there? If it doesn't work in the playground, please open a new issue with that reproduction.

If it works in the playground but not latest Next.js, feel free to open an issue on the Next.js repo and @ me there. Thanks!

**Comment by LouisCuvelier** [comment]
Done on #554

**Pull request merged**
