### PR TITLE
feat: Experimental support for custom Tailwind configurations

### PR DESCRIPTION
**Pull request by marcbouchenoire**
This PR adds a `tailwindConfig` option to pass a custom configuration down to `twrnc`, which allows sharing tokens between front-end and OG images in a single codebase already using Tailwind.

Custom Tailwind classes used in Satori's playground

#### Tests

I wasn't sure if I should add tests given that Tailwind support is labeled `experimental` and that there are no Tailwind-related tests currently.

#### `@vercel/og`

What's the process like to surface new `satori` features up to `@vercel/og`? (e.g. adding a `tailwindConfig` option there too)

### CODE REVIEW

**Comment by shuding** [comment]
Thanks for opening this PR! The tricky thing about Tailwind CSS support in Satori is, we are still undecided on the final implementation (hence why we said it's experimental). 

`twrnc` is currently a workaround as it's made for RN, but Satori is a different environment. Things like shadows don't work the same in RN so I think in the longer term, we definitely need to re-consider the entire thing.

Ideally we need a lightweight transpiler for Tailwind classes that only generates inlined styles. This means that media queries and pseudo elements, hover states, CSS selectors, etc. won't (and shouldn't work) in Satori.

Overall we can take this PR but we can't guarantee how long are we gonna keep it.

**Comment by marcbouchenoire** [comment]
Yeah, after I opened this PR I tried to use it in a side-project with `patch-package` and bumped into some of these limitations.

I think it's fair to close this PR to avoid creating any false hopes but if you think the basic value this currently provides (e.g. custom brand colors for text, etc) is worth it even if it's temporary, I'll leave it up to you. 🙂

**Comment by shuding** [comment]
I'm going to still merge it so in the future we will have the configuration API in mind when we think it's good to be a stable feature 👍

**Comment by kieranm** [comment]
@marcbouchenoire @shuding Do you know if it's possible to access this config option through `ImageResponse`? Just trying to figure out how to use it with the `opengraph-image` files in Next 13. Thanks!

**Pull request merged**
