### PR TITLE
fix: Add support for non-breaking space

### LINKED ISSUE #293: Support Non-breaking space
# Feature Request

## Description

Allow `<span>Word1 Word2&nbsp;Word3</span>` to work as expected: Carries down both Word2 and Word3 to a new line if needed

## Additional Context

Example of non breaking space not working: https://og-playground.vercel.app/?share=nZBPS8QwEMW_ShiRvRQ2_kEk1AVRwbvCXnJpm2kbTTOlTV1rzHc36boie9xc8ub3mGHmeahIIQjIlf6QlrHRzQbvvE-asRZ10zrBVhecn6-yPdxp5dojpvTYm2KOtDb4eaBJP-oBK6fJRq8iM3X24JZF9d4MNFn1QIaG6J_Vdf3XS9a96C8U7OryH9r-bnTD-UJDkHaTRD72hd14Cd8nvGc0hqScOL_nWxqMkhDy9TJR2nwds4k_ZEB9umQE4WFJAcRt3AP2MYG4ToXCcmpA1IUZMQPs6E2_zn3K2O2WKs5Jlzx1JSoQbpgwhB8

Thank you for releasing such an excellent open source library!

### PR DESCRIPTION
**Pull request by sahithyandev**
fixes #293.

### CODE REVIEW

**Review by shuding — COMMENTED** [review]
Can you please add a test case for it? Thanks!

**Comment by sahithyandev** [comment]
I have added a test.

**Comment by shuding** [comment]
Thanks!

**Comment by tvler** [comment]
Thanks for working on this. much appreciated!

**Pull request merged**
