### PR TITLE
fix: playground current color stopped working

### PR DESCRIPTION
**Pull request by LuciNyan**
image

Closes: #288

### CODE REVIEW

**Comment by jueungrace** [comment]
@LuciNyan thanks for adding this! your work would solve for when a user passes in `color: currentcolor` but not for "borders, backgrounds, non-text elements etc." (see more [here](https://github.com/styled-components/css-to-react-native/issues/170) in the issue i've brought up to css-to-react-native library). like jacob mentioned in his comment in that issue, full currentcolor support would require more complex layering! i suggest we amend documentation/readme.md to explicitly call out that `currentcolor` works for `color` and not other properties where `currentcolor` can typically be passed in 👍🏻

**Review by jueungrace — APPROVED** [review]

**Comment by shuding** [comment]
Thank you both @LuciNyan @jueungrace for fixing this, great work! 

> i suggest we amend documentation/readme.md to explicitly call out that currentcolor works for color and not other properties where currentcolor can typically be passed in 👍🏻

Makes total sense! There's another case that maybe we can address, which is a lot of SVGs (especially icon libs) are using `currentColor` as the fill/stroke color and it might not be working here ([example](https://og-playground.vercel.app/?share=XVLBbsIwDP2VKNPEhUEHpYwIOIxNYoedhsSll9K4JSxtqjQFStV_n9NSxDjFfi_Oe3Zc0VBxoIzOuTj6KSG5KSUsqsrGhOxBxHvDSO_VcZ57_RY8CW72DxgXeSaDEtFIwrlDbfwhNIRGqBS5UMkiSTs2kCJOvwwkuaUgNaA76lDkRkTlSiGYWv3_9C4If2OtipSvlFQa-acoim6qWPUjLsDIeHQHba-9eI5zRdFOU6yBt7V17adLG8zzY3zX7MKn04lPW-Qo4PSuzog5xCHTCfFuVCSkRDwstEa_jbeO6uZKkkDHwg7D1mbnXiNKSCOLwllg9oTjI9_j6WAyG4wmcuwNZqjirgee2yYvnnvx6XI-tLdbw0N03Eb4kY9qG5Ux4jootVyDlKpPtkpLPh_iXSzqTtqnKrNflVNW0aZzyt5wXLTdA8pcm3DYFTFlUSBz6FNI1EFsyswukTk1Gb5jB_6Z7IBTZnQBdf0H)).

I'll merge this one and open a new issue to track those :)

**Comment by jueungrace** [comment]
> Thank you both @LuciNyan @jueungrace for fixing this, great work!

all credit goes to luci! :)

**Comment by LuciNyan** [comment]
Thanks @jueungrace! You're so sweet! You just made my day! ❤️

**Pull request merged**
