### PR TITLE
chore: regenerated image snapshots name

### PR DESCRIPTION
**Pull request by Yana-Gupta**
Hi @Jackie1210 ,
I have regenerated snapshots name.

### CODE REVIEW

**Comment by Jackie1210** [comment]
@Yana-Gupta yeah, but why do you open another PR?

**Comment by Yana-Gupta** [comment]
Hi there, I am new to open source so didn't know.

**Comment by Yana-Gupta** [comment]
@Jackie1210 , do you know why it is not able to get workflow approval till now.

**Comment by LuciNyan** [comment]
> @Jackie1210 , do you know why it is not able to get workflow approval till now.

It seems @shuding's approval is needed.

**Comment by shuding** [comment]
Thanks!

**Pull request merged**
