### PR TITLE
support flex gap

### PR DESCRIPTION
**Pull request by jeetiss**
hello,

I'm experimenting with [`yoga-wasm-web`](https://github.com/shuding/yoga-wasm-web) to support gaps in flexbox and it works 🙌🏻

it looks like WIP because I can't fix types and add mess `@ts-ignore` everywhere

EDIT: 

I compiled the new version of https://github.com/shuding/yoga-wasm-web/pull/3
and I was so excited about it that I failed to explain what I actually did)

### CODE REVIEW

**Comment by shuding** [comment]
It's interesting that gap already works, because that WASM build is based on an old commit that probably doesn't have gap... I'll figure out why...

**Comment by jeetiss** [comment]
No, it doesn't. I updated `yoga-wasm-web`

- https://github.com/shuding/yoga-wasm-web/pull/3

And generate images with patched version in `node_modules`

**Comment by shuding** [comment]
Released all the changes in `yoga-wasm-web`, but currently the blocker is that we need to fork https://github.com/vadimdemedes/yoga-layout-prebuilt to make it stick to the same commit of Yoga.

**Comment by jeetiss** [comment]
I checked `yoga-layout-prebuild` and it is compiled by [`nbind`](https://github.com/charto/nbind) that is obsolete (it works with node v0.10.x - v7.x.x (newer may also work))

Let's build `asm` with `emcc` it should be better! @shuding why did you remove `asm` build from [`yoga-wasm-web`](https://github.com/shuding/yoga-wasm-web)? And what do you think about returning it?

**Comment by jeetiss** [comment]
- https://github.com/shuding/yoga-wasm-web/pull/6

**Comment by shuding** [comment]
Amazing work!

**Pull request merged**
